### ISSUE TITLE
[BUG] Deploy action using JamesIves/github-pages-deploy-action

### ISSUE THREAD

**Issue by lmweber** [lcolladotor/biocthis#31]
Hi @lcolladotor , I'm not completely sure if this is the right place for this, but I found out there have been some changes to GitHub permissions / authentication affecting the deploy action with `JamesIves/github-pages-deploy-action` that we had in the OSTA GitHub Actions workflow.

Specifically, the line
```
uses: JamesIves/github-pages-deploy-action@releases/v3
```
needs to be updated to v4:
```
uses: JamesIves/github-pages-deploy-action@releases/v4
```
to use the latest version where @JamesIves has updated this.

I suspect the fix is in the updated handling of permissions in this release, although I'm not completely sure: https://github.com/JamesIves/github-pages-deploy-action/releases/tag/v4.3.3

Then, to use v4, some of the syntax for the action has also changed, specifically: `with: token` (lower-case `token` instead of `GITHUB_TOKEN`), and also lower-case for `with: branch` and `with: folder`. These changes are described in the release notes / migration guide here: https://github.com/JamesIves/github-pages-deploy-action/discussions/592

So now my Deploy action looks like this, which seems to be working:

```
      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main' && runner.os == 'Linux'
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: _book # The folder the action should deploy.
```

vs. the old version that no longer worked:

```
      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main' && runner.os == 'Linux'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: _book # The folder the action should deploy.
```

Here is also the error I was getting with v3 previously:

![Screen Shot 2022-07-06 at 01 40 02](https://user-images.githubusercontent.com/8062417/177476777-9c29d64a-bd27-43df-b7bb-afb4c3739ee1.png)

Also tagging @stephaniehicks for info.

Thank you!!
