### ISSUE TITLE
[FR] Improve `check-bioc.yml` action

### ISSUE THREAD

**Issue by nuno-agostinho** [lcolladotor/biocthis#8]
Hello! 

I really like the work you put into creating [`check-bioc.yml`][] and I used it as the basis to create my own GitHub Actions. Thank you for this amazing resource! However, I think the file is a bit complex to be understood and modified by novice users.

Here I present you some suggestions to improve on it. You can see an example of a [GitHub Action of mine in production](https://github.com/nuno-agostinho/psichomics/blob/master/.github/workflows/check-bioc.yml) with the suggestions that follow.

Please let me know what do you think! Again, thank you for your amazing work :)

### Branches to run on

First of all, I think all branches should be run on GitHubActions (with possible exceptions like `github-pages`). As an R/Bioconductor package developer, I have development branches to which I always want to run in GitHub Actions. So, instead of:

https://github.com/lcolladotor/biocthis/blob/3b96da142aef74df69f35664a13d1283359d5db5/actions/check-bioc.yml#L32-L40

We could have:

```yml
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages
```

### Windows, Mac and Linux builds

I would argue that [`check-bioc.yml`][]'s complexity narrows down to code redundancy largely due to testing the Linux build in a Docker image separately from Windows and Mac. Also, this also means that we have to wait for the Linux version to finish testing before running the build in Windows and Mac.

As such, maybe it would be best to remove the Docker part (an alternative would be to test Windows/Mac in Docker images, but GitHub Actions does not support this as far as I know).

### Build in both bioc-release and bioc-devel

I always like to know if there are issues with the code I am writing in both the release and development version of Bioconductor. This way, we know if something is going to break in a specific version of Bioconductor beforehand. My matrix configuration is like so:

```yml
matrix:
        config:
          - {os: windows-latest, biocversion: "release"}
          - {os: windows-latest, biocversion: "devel"}
          - {os: macOS-latest,   biocversion: "release"}
          - {os: macOS-latest,   biocversion: "devel"}
          - {os: ubuntu-latest,  biocversion: "release"}
          - {os: ubuntu-latest,  biocversion: "devel"}
```

To find the R version related with each version of Bioconductor, we can use bash:

```yml
      - name: Find R version to run
        run: |
          config="https://bioconductor.org/config.yaml"
          rversion=$(curl ${config} | \
            grep r_version_associated_with_${BIOCVERSION} | \
            grep -o "[0-9]*\.[0-9]*\.[0-9]*")
          echo "Using R ${rversion}..."
          echo "::set-output name=rversion::${rversion}"
        shell:
          bash {0}
```

### Ubuntu versions

When defining the Ubuntu version to test on, why is RSPM also defined?

https://github.com/lcolladotor/biocthis/blob/3b96da142aef74df69f35664a13d1283359d5db5/actions/check-bioc.yml#L314

Although this is fine for specific versions of Ubuntu, a novice may simply update the version without understanding what the RSPM is and get confused with potential failures afterwards. I would suggest to either remove the RSPM variable or to add other Ubuntu versions with their respective RSPM values.

Also, I would suggest to put here `- {os: ubuntu-latest}`.

[`check-bioc.yml`]: https://github.com/lcolladotor/biocthis/blob/master/actions/check-bioc.yml
